[package]
name = "ipmi-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = { version = "0.26", default-features = false, features = ["ioctl"] }
log = "0.4"
time = { version = "0.3", optional = true, default-features = false, features = [ "formatting" ] }
nonmax = "0.5"
bitflags = "1.3"
finte = "0.2"

[dev-dependencies.pretty_env_logger]
version = "0.4"

[features]
default = [ "time" ]