name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  check-format:
    runs-on: ubuntu-latest
    name: Format
    strategy:
      matrix:
        crate:
          - ipmi-rs-core
          - ipmi-rs-log
          - ipmi-rs
    steps:
      - uses: actions/checkout@v5
      - name: Run cargo fmt
        run: cargo fmt --check -p ${{ matrix.crate }}

  check:
    runs-on: ubuntu-latest
    name: Check
    strategy:
      matrix:
        command:
          - "-p ipmi-rs-core --no-default-features"
          - "-p ipmi-rs-core --no-default-features -F time"
          - "-p ipmi-rs-core --no-default-features -F log"
          - "-p ipmi-rs-core --all-features"
          - "-p ipmi-rs-core --examples"
          - "-p ipmi-rs-core --no-default-features --examples"

          - "-p ipmi-rs-log --no-default-features"
          - "-p ipmi-rs-log --no-default-features -F log-to-file"
          - "-p ipmi-rs-log --all-features"
          - "-p ipmi-rs-log --examples"
          - "-p ipmi-rs-log --no-default-features --examples"

          - "-p ipmi-rs --no-default-features"
          - "-p ipmi-rs --no-default-features -F md5"
          - "-p ipmi-rs --no-default-features -F unix-file"
          - "-p ipmi-rs --all-features"
          - "-p ipmi-rs --examples"
          - "-p ipmi-rs --no-default-features --examples"
    steps:
      - uses: actions/checkout@v5
      - name: Check a package with specific feature combination.
        run: CARGO_BUILD_WARNINGS=deny cargo check --locked ${{ matrix.command }}

  test:
    runs-on: ubuntu-latest
    name: Test
    strategy:
      matrix:
        command:
          - "-p ipmi-rs-core --no-default-features"
          - "-p ipmi-rs-core --no-default-features -F time"
          - "-p ipmi-rs-core --no-default-features -F log"
          - "-p ipmi-rs-core --all-features"

          - "-p ipmi-rs-log --no-default-features"
          - "-p ipmi-rs-log --no-default-features -F log-to-file"
          - "-p ipmi-rs-log --all-features"

          - "-p ipmi-rs --no-default-features"
          - "-p ipmi-rs --no-default-features -F md5"
          - "-p ipmi-rs --no-default-features -F unix-file"
          - "-p ipmi-rs --all-features"
    steps:
      - uses: actions/checkout@v5
      - name: Check a package with specific feature combination.
        run: cargo test --locked ${{ matrix.command }}

  clippy:
    runs-on: ubuntu-latest
    name: clippy
    strategy:
      matrix:
        crate:
          - ipmi-rs-core
          - ipmi-rs-log
          - ipmi-rs
    steps:
      - uses: actions/checkout@v5
      - name: Run cargo clippy
        run: cargo clippy --locked --all-features -p ${{ matrix.crate }} -- -Dwarnings

  ci-success:
    runs-on: ubuntu-latest
    needs: [check-format, check, test, clippy]
    steps:
      - run: true
